'use strict';
const el=id=>document.getElementById(id);let active,cursor=0,timer,filename;
async function api(path,options){const r=await fetch(path,options);if(!r.ok){const e=await r.json();throw new Error(e.error)}return r}
function log(value){el('events').textContent+=`${JSON.stringify(value)}\n`;el('events').scrollTop=el('events').scrollHeight}
async function poll(){if(!active)return;try{const data=await(await api(`/api/v1/sessions/${active}/events?after=${cursor}`)).json();data.events.forEach(log);cursor=data.cursor}catch(e){el('host-status').textContent=e.message;clearInterval(timer)}}
el('host-open').onclick=async()=>{try{const config=await(await api('/api/v1/config')).json();if(config.auth!=='none')throw new Error('Use a host backend in bearer mode. This local-only example intentionally accepts no API key.');const file=el('host-file').files[0];if(!file)throw new Error('Choose a document first.');if(file.size>config.maxUploadBytes)throw new Error('File exceeds configured size limit.');const s=await(await api('/api/v1/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,mode:el('host-mode').value})})).json();try{await api(`/api/v1/sessions/${s.id}/file`,{method:'PUT',body:file})}catch(e){await api(`/api/v1/sessions/${s.id}`,{method:'DELETE'});throw e}clearInterval(timer);active=s.id;filename=file.name;cursor=0;el('events').textContent='';el('pane').src=s.embedUrl;el('pane').hidden=false;el('host-fetch').disabled=false;el('host-delete').disabled=false;el('host-status').textContent=`Session ${s.id} · token expires ${s.tokenExpiresAt}`;await poll();timer=setInterval(poll,2000)}catch(e){el('host-status').textContent=e.message}};
el('host-fetch').onclick=async()=>{try{const r=await api(`/api/v1/sessions/${active}/file`),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);await poll()}catch(e){el('host-status').textContent=e.message}};
el('host-delete').onclick=async()=>{try{await api(`/api/v1/sessions/${active}`,{method:'DELETE'});clearInterval(timer);active=null;el('pane').src='about:blank';el('pane').hidden=true;el('host-fetch').disabled=el('host-delete').disabled=true;el('host-status').textContent='Session and stored bytes deleted.'}catch(e){el('host-status').textContent=e.message}};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==el('pane').contentWindow||e.data?.source!=='nativepane'||e.data.sessionId!==active)return;log({browserHint:e.data.type,revision:e.data.revision})});
